INSERT INTO DEPARTMENT (DEPARTMENT_ID,DEPARTMENT_NAME, LOCATION) VALUES (1,'HR', 'New York');
INSERT INTO DEPARTMENT (DEPARTMENT_ID,DEPARTMENT_NAME, LOCATION) VALUES (2,'Finance', 'London');
INSERT INTO DEPARTMENT (DEPARTMENT_ID,DEPARTMENT_NAME, LOCATION) VALUES (3,'IT', 'Bangalore');
INSERT INTO DEPARTMENT (DEPARTMENT_ID,DEPARTMENT_NAME, LOCATION) VALUES (4,'Developer', 'Chennai');
